source 'https://github.com/CocoaPods/Specs.git'

# Required for Swift apps
platform :ios, '10.0'
use_frameworks!

def netalo_pods
  # use_modular_headers!
  use_frameworks!
  
  pod 'MessageKit', :git => 'http://gitlab.ecdc.vn/hieubui/nt-messagekit'
  pod 'Localize-Swift', :git => 'http://gitlab.ecdc.vn/hieubui/nt-Localize-Swift'
  pod 'Kingfisher', '~> 5.15'
  pod 'ReSwift', '~> 4.1.1'
  pod 'ReSwiftThunk', git: 'https://github.com/thanhphong-tran/ReSwift-Thunk.git', :tag => '1.1.1'
  pod 'SwipeTransition', '~> 0.4.2'
  pod 'GoogleWebRTC', '~> 1.1'
  # Local database
  pod 'Realm', '5.3.5'
  pod 'RealmSwift', '5.3.5'
  pod 'Reachability', '~> 3.2'
  # Localization 2.0
  pod 'ZIPFoundation', '~> 0.9'
  # Secret chat
  pod 'SignalCoreKit', git: 'https://github.com/signalapp/SignalCoreKit.git'
  pod 'AxolotlKit', git: 'https://github.com/signalapp/SignalProtocolKit.git', branch: 'master'
  pod 'HKDFKit', git: 'https://github.com/signalapp/HKDFKit.git'
  pod 'Curve25519Kit', git: 'https://github.com/signalapp/Curve25519Kit'
  pod 'GRKOpenSSLFramework', git: 'https://github.com/signalapp/GRKOpenSSLFramework', branch: 'mkirk/1.0.2t'
  pod 'Socket.IO-Client-Swift', '14.0.0'
#  pod 'NetaloCommonSDK', :path => '/Users/phong/Desktop/IOS/NetaloCommonSDK'
  pod 'NetaloCommonSDK', :git => 'http://gitlab.ecdc.vn/hieubui/NetaloCommonSDK', branch: 'lomo-v12'
  
end

# The target name is most likely the name of your project.
target 'TestReactNativeV3' do

  netalo_pods
  
end
